version: 2
registries:
  maven-github:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/fp-felles
    username: x-access-token
    password: ${{ secrets.READER_TOKEN }}

updates:
  - package-ecosystem: github-actions
    directory: ".github/workflows"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
      exclude:
        - "no.nav.*"
    open-pull-requests-limit: 10
  - package-ecosystem: maven
    directory: "/"
    registries:
      - maven-github
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
      exclude:
        - "no.nav.*"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
    groups:
      prod-deps:
        dependency-type: "production"
        exclude-patterns:
          - "no.nav.*"
      dev-deps:
        dependency-type: "development"
        exclude-patterns:
          - "no.nav.*"
      interne-deps:
        patterns:
          - "no.nav.*"
