version: '3.7'
services:
  postgres:
    image: postgres:18
    environment:
      PGPORT: 5999
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - "5999:5999"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d/
    container_name: postgres_formidling
  vtp:
    image: europe-north1-docker.pkg.dev/nais-management-233d/teamforeldrepenger/navikt/vtp:latest
    environment:
      TZ: Europe/Oslo
      NO_NAV_MODIG_SECURITY_APPCERT_KEYSTORE: /app/.modig/keystore.jks
      JAVAX_NET_SSxsL_TRUSTSTORE: /app/.modig/truststore.jks
    env_file:
      - "vtp.env"
    volumes:
      - "~/.modig:/app/.modig"
    ports:
      - "8060:8060"
      - "8063:8063"
      - "8636:8636"
      - "9093:9093"
      - "9092:9092"
      - "8389:8389"
    container_name: vtp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8060/rest/isReady"]
      interval: 30s
      timeout: 5s

